language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql
  - DB=pgsql

before_install:
  - cp tests/TestConfiguration.travis-${DB}.php tests/TestConfiguration.php
  - cp tests/config/local.php config/autoload/local.php
  - cp tests/phpunit.xml.dist tests/phpunit.xml
  - curl -s getcomposer.org/installer | php -d detect_unicode=Off
  - php composer.phar install --dev --prefer-source --no-interaction
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "short_open_tag = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS gotcms_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE gotcms_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS gotcms_tests;'; fi"

script:
  - ./scripts/phpcs.sh
  - ./scripts/runtests.sh

after_script:
  - php scripts/coveralls -v --exclude-no-stmt
