language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5
env:
  - DB=mysql
  - DB=pgsql

before_install:
  - cp tests/TestConfiguration.travis-${DB}.php tests/TestConfiguration.php
  - cp tests/config/global.php config/autoload/global.php
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source --no-interaction
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini


before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS gotcms_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE gotcms_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS gotcms_tests;'; fi"

script: ./tests/runtests.sh

after_script:
  - php vendor/bin/coveralls -v --exclude-no-stmt

